name: build

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: levonet
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare tags
      if: ${{ github.ref_type == 'tag' }}
      id: tags
      uses: actions/github-script@v4
      with:
        script: |
          const tags = context.ref_name.split('-')
          setOutput('jaeger', tags[0])
          setOutput('jaeger-clickhouse', tags[1])

    - name: Docker meta
      id: meta-jaeger
      uses: docker/metadata-action@v3
      with:
        images: levonet/jaeger
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=match,pattern=v(\d+.\d+.\d+),group=1
        flavor: |
          latest=auto
          suffix=-bullseye,onlatest=false

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          JAEGER_VERSION=${{ steps.tags.outputs.jaeger || 'master' }}
          JAEGER_CLICKHOUSE_VERSION=${{ steps.tags.outputs.jaeger-clickhouse || 'main' }}
        load: true
        tags: ${{ fromJSON(steps.meta-jaeger.outputs.json).tags[0] }}

    # - name: Run test
    #   env:
    #     JAEGER_TAG: ${{ fromJSON(steps.meta-jaeger.outputs.json).tags[0] }}
    #   run: |
    #     cd test
    #     make test

    - name: Build and push
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta-jaeger.outputs.tags }}
        labels: ${{ steps.meta-jaeger.outputs.labels }}

    - name: Docker Hub Description
      if: ${{ github.event_name != 'pull_request' }}
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: levonet/jaeger
